#### 1.  Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [2]:
import numpy as np


In [3]:
a = np.arange(12, 24)

In [4]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [6]:
b1 = a.reshape(6,2)
b2 = a.reshape(2,6)
b3 = a.reshape(3,4)
b4 = a.reshape(4,3)
b5 = a.reshape(12,1)
b1, b2, b3, b4, b5

(array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [7]:
c1 = np.reshape(a,(3, -1))
c2 = np.reshape(a,(-1, 3))
c3 = np.reshape(a,(-1, 4))
c4 = np.reshape(a,(4, -1))
c5 = np.reshape(a,(-1, 6))
c6 = np.reshape(a,(6, -1))
c1, c2, c3, c4, c5,c6


(array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]))

#### 5.Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [11]:
b=np.random.sample((3,4))
b

array([[0.52557776, 0.30813441, 0.42430256, 0.12263598],
       [0.60705692, 0.46452643, 0.57932027, 0.21361313],
       [0.31413524, 0.17931796, 0.96770748, 0.07362679]])

In [12]:
bc=b.flatten()
bc

array([0.52557776, 0.30813441, 0.42430256, 0.12263598, 0.60705692,
       0.46452643, 0.57932027, 0.21361313, 0.31413524, 0.17931796,
       0.96770748, 0.07362679])

#### 6.Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [13]:
za=np.arange(20,0,-2)
za

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 7.Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [14]:
zb = np.arange(20, 1, -2)
zb

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [15]:
if np.array_equal(za, zb):
    print('Массивы одинаковые')
else:
    print('Массивы не одинаковые')

Массивы одинаковые


#### 8.Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [24]:
ab1=np.zeros((2,2))
ab2=np.ones((3,2))
d=np.vstack((ab1,ab2))
d

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
d.size

10

#### 9.Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [27]:
a=np.arange(12)
ma=a.reshape(4,3)
ma

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
At=ma.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [29]:
B=ma.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [30]:
B.size

16

In [31]:
detB=np.linalg.det(B)
detB

0.0

Матрицу, обратную В, получить нельзя. Нарушено условие существования обратной матрицы.

#### 10.Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [32]:
import random
random.seed(42)
np.random.random()

0.551640880508571

#### 11.Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [33]:
c=np.random.randint(0,16,16)
c

array([ 8,  6,  8,  9,  3, 12,  0,  7,  1, 12,  2, 15, 13, 14,  6,  0])

#### 12.Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [34]:
C=c.reshape(4,4)
C

array([[ 8,  6,  8,  9],
       [ 3, 12,  0,  7],
       [ 1, 12,  2, 15],
       [13, 14,  6,  0]])

In [36]:
D = C*10 + B
D

array([[ 85,  74, 103, 122],
       [ 44, 170,  86, 192],
       [ 33, 206, 169, 362],
       [162, 262, 272, 302]])

In [37]:
detD=np.linalg.det(D)
detD

-118698200.0

In [39]:
rankD=np.linalg.matrix_rank(D)
rankD

4

In [40]:
D_inv= np.linalg.inv(D)
D_inv

array([[ 0.02526829,  0.01083049, -0.00710221, -0.00858008],
       [-0.01207786,  0.01063554, -0.00535796,  0.00453992],
       [-0.01762504, -0.01843431,  0.00460849,  0.01331579],
       [ 0.01279784,  0.00156649,  0.00430739, -0.00801781]])

#### 13.Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [43]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 1., 1.],
       [1., 1., 1., 0.]])

In [45]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,   8,   9],
       [  3,  50,   0, 122],
       [  1,  12, 149, 212],
       [ 32, 122, 212,   0]])